package:
  name: blackfire
  version: 2.29.0
  epoch: 0
  description: "Blackfire CLI"
  copyright:
    - license: PROPRIETARY
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/x86_64
      expected-sha512: b9a46c12a290fdf87c8f980551349099e8dbe7c0d582e0d99a2088cde04b05ef4ca31331e7b4878d15ba7b211c93ea9fe57baeec983e2836e6f8a3e8c0767086

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/aarch64
      expected-sha512: 15bde479458094262f2abeca90e1154346ee173cec44f650b150e8346f25a86860c173e55530eac1cf3f83998dcd9753f790a76cdbdeb047b0d5bee0851b8d1e

  - runs: |
      tar xfv ${{build.arch}}
      mkdir -p ${{targets.destdir}}/usr/bin
      mv blackfire ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 372834

test:
  pipeline:
    - runs: |
        blackfire version
