package:
  name: blackfire
  version: 2026.4.1
  epoch: 0
  description: "Blackfire CLI"
  copyright:
    - license: PROPRIETARY
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/x86_64
      expected-sha512: bbec05ec2686b09ffb50fafe04c5fcf7974f0b79a217e441b39aa8011b54a781f55eb89c19c64c8d157bca1ad79690f9380ec2680a3d9edb5fae8a240f82efaf

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/aarch64
      expected-sha512: 6699ad3697f3cd693a35ac5f1cdba952be435a06e9b3732a4ebcc18c7a067ccf5fd067c1c5c574388b53c46ebd0ea999ed22f277c762d11530afa7e31601985f

  - runs: |
      tar xfv ${{build.arch}}
      mkdir -p ${{targets.destdir}}/usr/bin
      mv blackfire ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 372834

test:
  pipeline:
    - runs: |
        blackfire version
