package:
  name: blackfire
  version: 2026.4.2
  epoch: 0
  description: "Blackfire CLI"
  copyright:
    - license: PROPRIETARY
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/x86_64
      expected-sha512: 8054c6aa53a1ef82ffdf5f3d8fff9c95b5f5997a22f54262e1460e14b98a262b3d6c6f557562500eebf6df040113e6b15a5cc024c3a90ec72c77b7eef4e58b44

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/aarch64
      expected-sha512: e1571ec69054d3873e358dc76d1e28d333106f69c54c6cbae9c7e0010116fe6c58bdc15ed3927f926495769cd8bcc83c1ffdd76b63ba46e68bee536829ac985d

  - runs: |
      tar xfv ${{build.arch}}
      mkdir -p ${{targets.destdir}}/usr/bin
      mv blackfire ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 372834

test:
  pipeline:
    - runs: |
        blackfire version
