package:
  name: blackfire
  version: 2026.4.0
  epoch: 0
  description: "Blackfire CLI"
  copyright:
    - license: PROPRIETARY
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/x86_64
      expected-sha512: e815d1c8c3876a94c902642d1bd07323dfd191cef50031332c0dbcf54bc719a39c2062772356210a421f8121fbdad0f7054720a2fbfbbb05733146d6c3aafdb2

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://blackfire.io/api/v1/releases/cli/linux/aarch64
      expected-sha512: 9d533ed886d547369dd1dcf4f204d5cc4e0cd8caa4be19d85bdc501e377a437fd9bfc21cc62e93ff16d983aa5e0cabfb44aead33de2694c3ef7526bf1ef9332b

  - runs: |
      tar xfv ${{build.arch}}
      mkdir -p ${{targets.destdir}}/usr/bin
      mv blackfire ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 372834

test:
  pipeline:
    - runs: |
        blackfire version
