package:
  name: bun-bin
  version: 1.1.23
  epoch: 0
  description: "Bun binary distrubution"
  copyright:
    - license: MIT
  options:
    no-provides: true

environment:
  contents:
    packages:
      - bash
      - busybox
      - curl

pipeline:
  - runs: |
      curl -fsSL https://bun.sh/install | bash -s "bun-v${{package.version}}"
      mkdir -p ${{targets.destdir}}/usr/bin
      mv $HOME/.bun/bin/* ${{targets.destdir}}/usr/bin/

      # symlink bunx as bun: https://github.com/oven-sh/bun/blob/main/dockerhub/distroless/Dockerfile#L70
      ln -s /usr/bin/bun ${{targets.destdir}}/usr/bin/bunx

update:
  enabled: true
  github:
    identifier: oven-sh/bun
    use-tag: true
    strip-prefix: bun-v

test:
  pipeline:
    - runs: |
        bun --version
        touch foo.js
        bunx prettier foo.js
