package:
  name: frankenphp-8.2
  version: 1.2.5
  epoch: 0
  description: "FrankenPHP"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - brotli-dev
      - build-base
      - busybox
      - caddy-src
      - go
      - libxml2-dev
      - php-frankenphp-8.2
      - php-frankenphp-8.2-dev
      - readline-dev
      - sqlite-dev
      - xcaddy

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}/var/www/html"
      echo "<?php phpinfo();" > ${{targets.destdir}}/var/www/html/index.php

      mkdir -p "${{targets.destdir}}/etc/caddy/"
      cat <<EOF > "${{targets.destdir}}/etc/caddy/Caddyfile"
      {
        # Enable FrankenPHP
        frankenphp
        # Configure when the directive must be executed
        order php_server before file_server
      }

      :8000 {
        root * /var/www/html
        # Enable compression (optional)
        encode zstd br gzip
        # Execute PHP files in the current directory and serve assets
        php_server
      }
      EOF

  - uses: git-checkout
    with:
      repository: https://github.com/dunglas/frankenphp
      tag: "v${{package.version}}"
      expected-commit: dcf190ebcb5817fad38a7e2a27991e28b4e240cf

  - name: Build
    runs: |
      export CGO_CFLAGS=$(php-config --includes)
      export CGO_LDFLAGS="$(php-config --ldflags) $(php-config --libs)"
      export XCADDY_GO_BUILD_FLAGS="-ldflags '-w -s'"
      export CGO_ENABLED=1

      mkdir -p ${{targets.destdir}}/usr/bin/

      xcaddy build \
        --output ${{targets.destdir}}/usr/bin/frankenphp \
        --with github.com/dunglas/frankenphp=./ \
        --with github.com/dunglas/frankenphp/caddy=./caddy/ \
        --with github.com/caddyserver/caddy/v2=/usr/src/caddy \
        --with github.com/dunglas/caddy-cbrotli \
        --with github.com/dunglas/mercure/caddy \
        --with github.com/dunglas/vulcain/caddy

  - uses: strip

update:
  enabled: true
  github:
    identifier: dunglas/frankenphp
    strip-prefix: v
    tag-filter: v
