package:
  name: libwatcher-c
  version: 0.14.1
  epoch: 0
  description: "Filesystem watcher. Works anywhere. Simple, efficient and friendly"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/e-dant/watcher
      tag: "${{package.version}}"
      expected-commit: f88ec3b7e1464d542c75c9832d012285dd4adc21

  - name: Build
    runs: |
      cd watcher-c
      c++ -o libwatcher-c.so ./src/watcher-c.cpp -I ./include -I ../include -std=c++17 -fPIC -shared
      mkdir -p ${{targets.destdir}}/usr/lib/
      cp libwatcher-c.so ${{targets.destdir}}/usr/lib/libwatcher-c.so
      mkdir -p ${{targets.destdir}}/usr/include/
      cp -r include/wtr ${{targets.destdir}}/usr/include/wtr
      ldconfig

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ${{package.name}}
    description: ${{package.name}} dev

update:
  enabled: true
  github:
    identifier: e-dant/watcher
    strip-prefix: release/
    tag-filter: release/
    use-tag: true
