package:
  name: php-8.1-blackfire
  version: 1.92.26
  epoch: 0
  description: "Blackfire PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.1

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_amd64-php-81.so
      expected-sha512: 9ad0262f52438a76dc6b4c6bb513649273204748e6aa75586a63ea2740c3230317b9092f7b24346fe91eab73048e0fa0e7a65998cbed3be6a5e453b20d313b4b
      extract: false

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_arm64-php-81.so
      expected-sha512: 7f14dd4d020bfe096e43e7e4d39904a549da9c52436fb7a1122e5d0b95a80468990039d42ff1f0ca063980a95441ed9eccd984fee84a06321aaaf9e418a7f508
      extract: false

  - name: Copy
    if: ${{build.arch}} == 'x86_64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_amd64-php-81.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

  - name: Copy
    if: ${{build.arch}} == 'aarch64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_arm64-php-81.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=blackfire.so" > "${{targets.subpkgdir}}/etc/php/conf.d/blackfire.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371867
