package:
  name: php-frankenphp-8.2-opentelemetry
  version: 1.2.1
  epoch: 0
  description: "OpenTelemetry PHP auto-instrumentation extension"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.2
      - php-frankenphp-8.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-php-instrumentation
      tag: ${{package.version}}
      expected-commit: c5ebd70d50d9d25a0628c2ae0bfb6e516b551838

  - name: Prepare build
    runs: cd ext && phpize

  - name: Configure
    runs: |
      set -x
      cd ext
      ./configure

  - name: Make install
    runs: |
      set -x
      cd ext
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=opentelemetry.so" > "${{targets.subpkgdir}}/etc/php/conf.d/opentelemetry.ini"

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-php-instrumentation
