package:
  name: php-frankenphp-8.2-phalcon
  version: 5.9.1
  epoch: 0
  description: "Phalcon is a full stack PHP framework offering low resource consumption and high performance"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.2
      - php-frankenphp-8.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/phalcon/cphalcon
      tag: "v${{package.version}}"
      expected-commit: 7903161c2bc7ef378b707cf46df368ca2f6ff72f

  - name: Prepare build
    working-directory: ext
    runs: phpize

  - name: Build
    working-directory: ext
    runs: ./configure

  - name: Make install
    working-directory: ext
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=phalcon.so" > "${{targets.subpkgdir}}/etc/php/conf.d/phalcon.ini"

update:
  enabled: true
  github:
    identifier: phalcon/cphalcon
    strip-prefix: v
    tag-filter: v
    use-tag: true
