package:
  name: php-8.4-relay
  version: 0.21.0
  epoch: 0
  description: "Relay is a Redis™ client like PhpRedis and Predis, except two orders of magnitude faster"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - liblz4-1
      - libzstd1
      - php-8.4
      - php-8.4-igbinary
      - php-8.4-msgpack

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.4-debian-x86-64+libssl3.tar.gz
      expected-sha512: c8be2b29b622d15fe2d54149e1a675b6d1c298791d74ca9eb461bc175cedb47a4cc7f9a9773c7b0676896418143ae8d32722d75723559afebd6f35f8b260b42f

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.4-debian-aarch64+libssl3.tar.gz
      expected-sha512: c46d4c0edd16ec0b0186efb1e2b6c36e47fb63119a4b1ef11f9fff78ae76c12b5901772dde392b0096db892e8d579a2d724f2b2405987099536eefa4695de13c

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp relay-pkg.so ${{targets.destdir}}/usr/lib/php/modules/relay.so
      sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" ${{targets.destdir}}/usr/lib/php/modules/relay.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=relay.so" > "${{targets.subpkgdir}}/etc/php/conf.d/relay.ini"

update:
  enabled: true
  release-monitor:
    identifier: 375123
