package:
  name: php-8.4-blackfire
  version: 2026.4.1
  epoch: 0
  description: "Blackfire PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.4

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_amd64-php-84.so
      expected-sha512: e71418b7d67b37ecfdbcb1b9b27df2e26da851406f57cee288442c26a2db366dbbd4a5eead4549614d0429c22dba5d3be18ec5db811f94a8b123b1d925415e5b
      extract: false

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_arm64-php-84.so
      expected-sha512: a88755d37860854f0635865f5d9bf06705a92d56225ce0e0f358ccdb921c4b394d52c9e7a300c4e09da1bab88b32cd386a01ecbbfd953cfe3a7a18810a8c9e95
      extract: false

  - name: Copy
    if: ${{build.arch}} == 'x86_64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_amd64-php-84.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

  - name: Copy
    if: ${{build.arch}} == 'aarch64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_arm64-php-84.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=blackfire.so" > "${{targets.subpkgdir}}/etc/php/conf.d/blackfire.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371867
