package:
  name: php-frankenphp-8.5-protobuf
  version: 5.35.0
  epoch: 0
  description: "Protocol Buffers - Google's data interchange format"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.5

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.5
      - php-frankenphp-8.5-dev
      - protobuf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/protobuf-${{package.version}}.tgz
      expected-sha512: 7951fbe0926bb4be97a78dfc4b9627e79baf5004e4d37dd86afbfd720208928cd8103d4b9f98ae3c5b98def8dde9923b3f8ee5492214c640c1844383b2c8f6f3

  - name: Prepare build
    runs: phpize

  - name: Build
    runs: ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=protobuf.so" > "${{targets.subpkgdir}}/etc/php/conf.d/protobuf.ini"

update:
  enabled: true
  release-monitor:
    identifier: 141406
