package:
  name: php-frankenphp-8.4-grpc
  version: 1.75.1
  epoch: 0
  description: "A PHP extension for gRPC"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - grpc
      - php-frankenphp-8.4

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - grpc-dev
      - php-frankenphp-8.4
      - php-frankenphp-8.4-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc/grpc
      tag: "v${{package.version}}"
      expected-commit: 9b63ce0d513672c5daad4f28342f03863c5589e5

  - name: Prepare build
    runs: cd src/php/ext/grpc && phpize

  - name: Configure
    runs: cd src/php/ext/grpc && ./configure

  - name: Make install
    runs: |
      cd src/php/ext/grpc
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=grpc.so" > "${{targets.subpkgdir}}/etc/php/conf.d/grpc.ini"

update:
  enabled: true
  github:
    identifier: grpc/grpc
    strip-prefix: v
    tag-filter: v
