package:
  name: php-frankenphp-8.2-mongodb
  version: 2.3.3
  epoch: 0
  description: "MongoDB driver"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cyrus-sasl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev>3
      - php-frankenphp-8.2-dev
      - snappy-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/mongodb-${{package.version}}.tgz
      expected-sha512: ee83cd310a61920f6d047a6e45ca1ecc7b6ba9c80e24d69e1f6d45d2e3124dfb8a618fce1541868441ac275b6ebbdb274d4a06525f40dd8c05727eb380721a26

  - name: phpize and configure
    runs: |
      phpize
      ./configure --prefix=/usr --with-php-config=php-config

  - uses: autoconf/make

  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=mongodb.so" > ${{targets.destdir}}/etc/php/conf.d/mongodb.ini

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 11158
