package:
  name: php-8.3-relay
  version: 0.21.0
  epoch: 0
  description: "Relay is a Redis™ client like PhpRedis and Predis, except two orders of magnitude faster"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - liblz4-1
      - libzstd1
      - php-8.3
      - php-8.3-igbinary
      - php-8.3-msgpack

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.3-debian-x86-64+libssl3.tar.gz
      expected-sha512: 3f2b01d19ca355ea0bd8acc52ac68afa6ff9b1b85c60f054f9ebe8f30a19dc3be1229bc4ad404d1b2189b0a433399d43d03467934a0c3f8c58fd6e49e15201fb

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.3-debian-aarch64+libssl3.tar.gz
      expected-sha512: 836bef008d50a6eb092079a5d3fcd1d50d47a6539cadb24e9306918eef0d140bf66c50e6b1e5cd1a1b0bab3bf28da8a8bc69560661567907a335781a259d8251

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp relay-pkg.so ${{targets.destdir}}/usr/lib/php/modules/relay.so
      sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" ${{targets.destdir}}/usr/lib/php/modules/relay.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=relay.so" > "${{targets.subpkgdir}}/etc/php/conf.d/relay.ini"

update:
  enabled: true
  release-monitor:
    identifier: 375123
