package:
  name: php-frankenphp-8.5-tideways
  version: 5.42.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.5

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 7b03f90bf02576195bdf80437230dd6f65af000cefc05b15369aaaef21665474717e313c87f9e402ccfc56e68425151af8403c74074ec9c0f59d38ba02680a08

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: c8e042f83b7a1a4df185a76e1ddf749bb548927f156b728e1be67da1b7409249229a69b2527fea2cc13de7d7fa764421aeeb5365dbd22264bcb8571679b3b49f

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.5-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
