package:
  name: php-8.4-tideways
  version: 5.38.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.4

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 7c2af7d2587b1657d576be954a2ad45672750dfbca76a91c0d374c52b267ca797361829fca265b8bbb215bd28e8de0cca935b2de38797f1f3f02bf1a6bbeb03b

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 9491de232168193764473bc965f96d1e6875f2f8649cf0a66316ef444d759316b5875a3b8733e5056f921c77a60f2276444c5200aedd1772d813c3660a808dbe

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.4.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870

test:
  pipeline:
    - runs: |
        php -m | grep tideways
