package:
  name: php-8.1-tideways
  version: 5.40.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.1

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 0f0623b9cb4c671c5671376ac9c60da55362e1f495702fdfd5231590b9c72e83711c0e4480d2516ea791f1b60e70e0e34415e03c65c7339227181aff55b01257

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 74fc65fc6ec80e6397aa884c48215829f8fb155615b0ae409110a3f3f1b0bd0a3db9d2c378ac2c5f6303c053ecbfe8b9451dfee4b7c309c477c897b591e3cdde

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.1.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
