package:
  name: php-frankenphp-8.2-mongodb
  version: 2.2.1
  epoch: 0
  description: "MongoDB driver"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cyrus-sasl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev>3
      - php-frankenphp-8.2-dev
      - snappy-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/mongodb-${{package.version}}.tgz
      expected-sha512: ce9450d978c9031b7b8d199e7ad0d1ab7420ae8584d8926b2965f548375c4bd056968af90a731549f7077d95f0bbe1f54c819844d90eb4096be1079ae3d69561

  - name: phpize and configure
    runs: |
      phpize
      ./configure --prefix=/usr --with-php-config=php-config

  - uses: autoconf/make

  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=mongodb.so" > ${{targets.destdir}}/etc/php/conf.d/mongodb.ini

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 11158
