package:
  name: php-8.5-relay
  version: 0.30.0
  epoch: 0
  description: "Relay is a Redis™ client like PhpRedis and Predis, except two orders of magnitude faster"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - liblz4-1
      - libzstd1
      - php-8.5
      - php-8.5-igbinary
      - php-8.5-msgpack

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.5-debian-x86-64+libssl3.tar.gz
      expected-sha512: f58d5a283fa90b3acd518fc775cdfc6a60c0d2e68001ef0ba50445499d99b1a2f3db101d193c43ae9b42b8e26a53371b52a08112a6a7353ad46571e12f2ad644

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.5-debian-aarch64+libssl3.tar.gz
      expected-sha512: 4634aa9cad1ca101db09f4f87f1c85fdcae47c98e325fd2564345ce3199bfee0c3e33346b4a7447fe8e9761aec54b190697593eaae6dd264c3d73dce42a415af

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp relay-pkg.so ${{targets.destdir}}/usr/lib/php/modules/relay.so
      sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" ${{targets.destdir}}/usr/lib/php/modules/relay.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=relay.so" > "${{targets.subpkgdir}}/etc/php/conf.d/relay.ini"

update:
  enabled: true
  release-monitor:
    identifier: 375123
