package:
  name: php-frankenphp-8.4-protobuf
  version: 5.35.1
  epoch: 0
  description: "Protocol Buffers - Google's data interchange format"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.4

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.4
      - php-frankenphp-8.4-dev
      - protobuf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/protobuf-${{package.version}}.tgz
      expected-sha512: cec03a21e5c1c295e6040b7bd616a62fb6027330a5ddf7b8cf9d3fc5072ff46dd803657d03cda063c26def3ec84c94086823e218f637632bd87045a28fd5e80c

  - name: Prepare build
    runs: phpize

  - name: Build
    runs: ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=protobuf.so" > "${{targets.subpkgdir}}/etc/php/conf.d/protobuf.ini"

update:
  enabled: true
  release-monitor:
    identifier: 141406
