package:
  name: php-frankenphp-8.3-swoole
  version: 6.1.1
  epoch: 0
  description: "Coroutine-based concurrency library for PHP"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.3

environment:
  contents:
    packages:
      - autoconf
      - brotli-dev
      - build-base
      - busybox
      - php-frankenphp-8.3
      - php-frankenphp-8.3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/swoole/swoole-src
      tag: "v${{package.version}}"
      expected-commit: 9c0578bbc345f380878b6bd02bd2e50de99d3ed4

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: |
      set -x
      ./configure

  - uses: autoconf/make

  - name: Make install
    runs: |
      set -x
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=swoole.so" > "${{targets.subpkgdir}}/etc/php/conf.d/swoole.ini"

update:
  enabled: true
  github:
    identifier: swoole/swoole-src
    strip-prefix: v
    tag-filter: v
    use-tag: true
