package:
  name: php-frankenphp-8.2-mongodb
  version: 2.3.1
  epoch: 0
  description: "MongoDB driver"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cyrus-sasl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev>3
      - php-frankenphp-8.2-dev
      - snappy-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/mongodb-${{package.version}}.tgz
      expected-sha512: 1325734dc6b22a2475398e31b92eec610bc1a7924f01e3296fd6a1aebbfc4d10fa04f29810fa994170d1177c8b8d571a726a0f0c249c0f46c2b20a86fb5f7b8f

  - name: phpize and configure
    runs: |
      phpize
      ./configure --prefix=/usr --with-php-config=php-config

  - uses: autoconf/make

  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=mongodb.so" > ${{targets.destdir}}/etc/php/conf.d/mongodb.ini

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 11158
