package:
  name: php-8.2-excimer
  version: 1.2.0
  epoch: 0
  description: "Excimer is a PHP extension that provides an interrupting timer and a low-overhead sampling profiler."
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.2
environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.2
      - php-8.2-dev
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wikimedia/mediawiki-php-excimer
      tag: "${{package.version}}"
      expected-commit: 4cc649be12183c672867e9184d09d7cd9c604d91
  - name: Prepare build
    runs: phpize
  - name: Configure
    runs: |
      set -x
      ./configure
  - uses: autoconf/make
  - name: Make install
    runs: |
      set -x
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install
subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=excimer.so" > "${{targets.subpkgdir}}/etc/php/conf.d/excimer.ini"
update:
  enabled: true
  github:
    identifier: php-excimer/php-excimer
    use-tag: true
