package:
  name: php-frankenphp-8.3-redis
  version: 6.1.0
  epoch: 0
  description: "A PHP extension for Redis"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.3
      - php-frankenphp-8.3-igbinary

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.3
      - php-frankenphp-8.3-dev
      - php-frankenphp-8.3-igbinary-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/phpredis/phpredis
      tag: ${{package.version}}
      expected-commit: 5419cc9c60d1ee04163b4d5323dd0fb02fb4f8bb

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure --enable-redis-igbinary

  - uses: autoconf/make

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=redis.so" > "${{targets.subpkgdir}}/etc/php/conf.d/redis.ini"

  - name: ${{package.name}}-dev
    description: PHP 8.3 redis development headers
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: phpredis/phpredis
