package:
  name: php-frankenphp-8.3-mongodb
  version: 2.3.2
  epoch: 0
  description: "MongoDB driver"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - php-frankenphp-8.3

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - cyrus-sasl-dev
      - gcc
      - icu-dev
      - libtool
      - openssl-dev>3
      - php-frankenphp-8.3-dev
      - snappy-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/mongodb-${{package.version}}.tgz
      expected-sha512: 8364ae6056185f3396015ae50085b44400e78b7ef15a187f3041584d88036e8c611fa7a1d626a2b7ac513c68e949c6cca565d107cdb565e5fde8fd2eabb8a5ac

  - name: phpize and configure
    runs: |
      phpize
      ./configure --prefix=/usr --with-php-config=php-config

  - uses: autoconf/make

  - name: Install
    runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
      install -d ${{targets.destdir}}/etc/php/conf.d
      echo "extension=mongodb.so" > ${{targets.destdir}}/etc/php/conf.d/mongodb.ini

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 11158
