package:
  name: php-8.4-tideways
  version: 5.39.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.4

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: bcf65e3ff9b86a9c48d262eaa17c61683c7f9d79f098f1dde19377873ef533154d507c3f57a15c0fb625ebf7093896e03fee9197827dd890be167a3db8427a0f

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 00d7aeacef227b54e5d504dd975e30823f5720169691e5b00e2d4fc6be7d032d9b33c7bdb61af32fd0e58b1342de0f1bbae04147188578734de63faec5241962

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.4.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870

test:
  pipeline:
    - runs: |
        php -m | grep tideways
