package:
  name: php-frankenphp-8.2-apcu
  version: 5.1.25
  epoch: 0
  description: "PHP extension for User Cache"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.2
      - php-frankenphp-8.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/krakjoe/apcu
      tag: "v${{package.version}}"
      expected-commit: 616c72d58cfc2a7ffce7512f9ae91e49d2d06ab9

  - name: Prepare build
    runs: phpize

  - name: Build
    runs: |
      set -x
      ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=apcu.so" > "${{targets.subpkgdir}}/etc/php/conf.d/apcu.ini"

update:
  enabled: true
  github:
    identifier: krakjoe/apcu
    strip-prefix: v
    tag-filter: v
    use-tag: true
