package:
  name: php-frankenphp-8.5-imagick
  version: 3.8.1
  epoch: 0
  description: "PHP extension for ImageMagick"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - imagemagick
      - php-frankenphp-8.5

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - imagemagick-dev
      - php-frankenphp-8.5
      - php-frankenphp-8.5-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Imagick/imagick
      tag: "${{package.version}}"
      expected-commit: 70087bab33eab913e99ac77d64d04d1a2fd0b7b0

  # Apply package version template as `package.xml` does not seem to apply this automatically
  - runs: sed -i "s/@PACKAGE_VERSION@/${{package.version}}/g" ./*.h

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: |
      set -x
      ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=imagick.so" > "${{targets.subpkgdir}}/etc/php/conf.d/imagick.ini"

update:
  enabled: true
  github:
    identifier: Imagick/imagick
    use-tag: true
