package:
  name: php-frankenphp-8.5-protobuf
  version: 5.34.1
  epoch: 0
  description: "Protocol Buffers - Google's data interchange format"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.5

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-frankenphp-8.5
      - php-frankenphp-8.5-dev
      - protobuf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://pecl.php.net/get/protobuf-${{package.version}}.tgz
      expected-sha512: e83d5ebfe6bfc11202f52e7327b8ce0fcd607a44be42d07e4ea4785bbba71fcd56a99259e76439cc1f9edd16b04753280007ca40dc59bc442570a610b2b8084c

  - name: Prepare build
    runs: phpize

  - name: Build
    runs: ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=protobuf.so" > "${{targets.subpkgdir}}/etc/php/conf.d/protobuf.ini"

update:
  enabled: true
  release-monitor:
    identifier: 141406
