package:
  name: php-frankenphp-8.2-tideways
  version: 5.41.0
  epoch: 0
  description: "Tideways PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.2

environment:
  contents:
    packages:
      - busybox
      - wget

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-x86_64.tar.gz
      expected-sha512: 26d2607134d9c01617abc952d0d0bbc95ea25aee57bbf1bf6ac17c3f362fc8c88561aa231d09acfe21c657aa034c4309cf2b541a519b7e5d98b5d842cde55e35

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://tideways.s3.amazonaws.com/extension/${{package.version}}/tideways-php-${{package.version}}-arm64.tar.gz
      expected-sha512: 95019b182226df75f0a73c917e247f558f652ddf8bf5ea6e1c8ad6568ffd689fec4309b9388bf47ab7f79aa5f1a915349e1b60730c21957147647f3869e14769

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp tideways-php-8.2-zts.so ${{targets.destdir}}/usr/lib/php/modules/tideways.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=tideways.so" > "${{targets.subpkgdir}}/etc/php/conf.d/tideways.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371870
