package:
  name: php-8.4-relay
  version: 0.22.0
  epoch: 0
  description: "Relay is a Redis™ client like PhpRedis and Predis, except two orders of magnitude faster"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - liblz4-1
      - libzstd1
      - php-8.4
      - php-8.4-igbinary
      - php-8.4-msgpack

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.4-debian-x86-64+libssl3.tar.gz
      expected-sha512: 5fa7a5902c296fbd6aea0a451ce9af4ace98609a7f21e2dc8c4d7b5cd969e88fda2424534c534938f7d688558024335b2d350afee7d3351f7e268bea0831ba2c

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.4-debian-aarch64+libssl3.tar.gz
      expected-sha512: e950f3107a91f5a20ecf87703b3e1e8f33a6ab63191ac25fb40fd5913031f18e8ff6e84461d82416cdbe153e3b56591931e58a6fe98e4f9cb0008e86b2a284aa

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp relay-pkg.so ${{targets.destdir}}/usr/lib/php/modules/relay.so
      sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" ${{targets.destdir}}/usr/lib/php/modules/relay.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=relay.so" > "${{targets.subpkgdir}}/etc/php/conf.d/relay.ini"

update:
  enabled: true
  release-monitor:
    identifier: 375123
