package:
  name: php-8.2-blackfire
  version: 1.92.25
  epoch: 0
  description: "Blackfire PHP Probe"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.2

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_amd64-php-82.so
      expected-sha512: 36053065f97b69ff44b0c176f25adf69242b3a66de2ebfbefc67738d1bf97e8d54631f4d263c7d262b5b470f3efcee11144eba9b3eae329fc77c3631fe50207b
      extract: false

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://packages.blackfire.io/binaries/blackfire-php/${{package.version}}/blackfire-php-linux_arm64-php-82.so
      expected-sha512: 57336220e06d66771be31f908981fdd3129a5863c36419a9c3de39d2a4e50d74daf1260d8adba495b51692dc5d66289da3d4b8d4fbc90506f7d17c9ee479f8c5
      extract: false

  - name: Copy
    if: ${{build.arch}} == 'x86_64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_amd64-php-82.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

  - name: Copy
    if: ${{build.arch}} == 'aarch64'
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp blackfire-php-linux_arm64-php-82.so ${{targets.destdir}}/usr/lib/php/modules/blackfire.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=blackfire.so" > "${{targets.subpkgdir}}/etc/php/conf.d/blackfire.ini"

update:
  enabled: true
  release-monitor:
    identifier: 371867
