package:
  name: php-8.5-relay
  version: 0.21.0
  epoch: 0
  description: "Relay is a Redis™ client like PhpRedis and Predis, except two orders of magnitude faster"
  copyright:
    - license: PROPRIETARY
  dependencies:
    runtime:
      - ${{package.name}}-config
      - liblz4-1
      - libzstd1
      - php-8.5
      - php-8.5-igbinary
      - php-8.5-msgpack

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    if: ${{build.arch}} == 'x86_64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.5-debian-x86-64+libssl3.tar.gz
      expected-sha512: 40964cca0879ba5bfa87b44c85a78c274c75a2645e2a6e1365b0dfad0a4211122955db7ad4c1d5c889fe9e4dec42fa27438ad595508334a8f3b31cb883538154

  - uses: fetch
    if: ${{build.arch}} == 'aarch64'
    with:
      uri: https://builds.r2.relay.so/v${{package.version}}/relay-v${{package.version}}-php8.5-debian-aarch64+libssl3.tar.gz
      expected-sha512: 3c3da681cc84cc7e242ecc82ff59c881484109db0da0f11c3e524e9d925c4861c4055773eab11ee3dd30d562c05394ef334630eefed7bc7e2ea9cf6aadd1e34d

  - name: Copy
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/php/modules/
      cp relay-pkg.so ${{targets.destdir}}/usr/lib/php/modules/relay.so
      sed -i "s/00000000-0000-0000-0000-000000000000/$(cat /proc/sys/kernel/random/uuid)/" ${{targets.destdir}}/usr/lib/php/modules/relay.so

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=relay.so" > "${{targets.subpkgdir}}/etc/php/conf.d/relay.ini"

update:
  enabled: true
  release-monitor:
    identifier: 375123
