package:
  name: php-frankenphp-8.3-zstd
  version: 0.15.0
  epoch: 0
  description: Zstd Extension for PHP
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-frankenphp-8.3

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - file
      - php-frankenphp-8.3
      - php-frankenphp-8.3-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kjdev/php-ext-zstd
      tag: "${{package.version}}"
      expected-commit: 5637d458a2d5a53508207829b8703833e8f4ccc7

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure --with-libzstd

  - uses: autoconf/make

  - name: Make install
    runs: INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=zstd.so" > "${{targets.subpkgdir}}/etc/php/conf.d/zstd.ini"

update:
  enabled: true
  ignore-regex-patterns:
    - pie$
  github:
    identifier: kjdev/php-ext-zstd
    use-tag: true
